/**
 * langPacks — 内嵌语言包数据(原 bundle 活区 `const ai={};aj={};aq..bb={}`
 * 共 50 个"空对象":实为 5 种语言(EN/JA/ZH/KO/ES)×(9 个分区字典 + 1 个
 * 聚合根)的 i18n 数据,逐属性赋值填充,最终挂到 window.lang_EN/
 * lang_JA/lang_ZH/lang_KO/lang_ES,由 I18n(core/I18n,原 ah)按
 * view["lang_" + selected] 消费,缺词回退 lang_EN。
 *
 * 本文件由 final-clean.js 第 209643–210704 行机械提取生成(脚本
 * deob/gen-langpacks.js),键序与字符串字面量(含 \uXXXX 转义)原样保留。
 *
 * 原名对照(每语言 10 个 const):
 *   EN  ai mainMenu / aj notif / aq leaderboard / ar huds / as settingMenu /
 *       at hkMenu / au mouseMenu / av commandsMenu / aw themeMenu / ax 根
 *   JA  ay az aA aB aC aD aE aF aG aH(同序)
 *   ZH  aI aJ aK aL aM aN aO aP aQ aR
 *   KO  aS aT aU aV aW aX aY aZ b0 b1
 *   ES  b2 b3 b4 b5 b6 b7 b8 b9 ba bb
 *
 * 装配方式:启动时等效执行
 *   view.lang_EN = langEN; …(或传给 I18n 的 view 上挂载)。
 */

export const langEN = {
  mainMenu: {
    btn_settings: "Settings",
    btn_play: "Play",
    btn_spectate: "Spectate",
    btn_inputs: "Inputs",
    btn_theme: "Theme",
    input_tag1: "Tag",
    input_tag2: "Tag 2",
    input_pin: "Pin",
    input_nick: "Nickname",
    input_skinUrl: "Skin URL (imgur)",
    select_ffa: "FFA",
    select_party: "Party",
    select_teams: "Teams",
    select_experimental: "Experimental",
    input_token: "Party token",
    btn_join: "Join",
    btn_create: "Create",
  },
  notif: {
    cantPlay2Tag: "You can't play in double tag mode.",
    hsloNetConn: "Welcome to Astrio!",
    hsloNetDisconn: "Disconnected from Astrio!",
    invalidSkinUrl: "Invalid skin URL",
    login_lastSession: "Logged in from last session data.",
    sdk_error: "SDK not loaded",
    alreadyLoggedIn: "Already logged in.",
    login_success: "Logged in",
    login_error: "Login error!",
    logout: "Logged out",
    nickChangeInGame: "You can't change nickname while in game.",
    targeting_on: "Click a player to begin targeting.",
    targeting_off: "Targeting is turned off.",
    target_unnamed: "Cannot target unnamed players.",
    hsloSkin_noAcc: "Account does not exist.",
  },
  leaderboard: {
    title: "Astr.io",
  },
  huds: {
    enterChatMsg: "Enter chat message...",
    teamlist_title: "Team Players",
    score: "Score",
    num1position: "#1 position",
    paused: "Paused",
    targeting_bigCellVp: "FOLLOWING #1 PLAYER",
    targeting_followVp: "FREE ROAM",
    targeting_totalMass: "TOTAL MASS",
    targeting_players: "FOLLOWING PLAYERS",
  },
  settingMenu: {
    language: "Language",
    CellAnimation: "Animation delay",
    zoomSpeed: "Zoom speed",
    cameraSpeed: "Camera speed",
    autoZoom: "Auto zoom",
    autoHideText: "Auto hide text",
    teamTags: "Team Tags",
    hideHud: "Hide HUD",
    lbColors: "Leaderboard colors",
    hideOwnNick: "Hide own nick",
    hideOwnMass: "Hide own mass",
    cellNick: "Cell nick",
    cellMass: "Cell mass",
    nickShadow: "Nick shadow",
    massShadow: "Mass shadow",
    urlSkins: "Skins",
    hsloSkins: "Astrio Skins",
    food: "Food",
    vanillaGrid: "Vanilla grid",
    bgSectors: "Background sectors",
    activeTurnMarker: "Active cell border",
    cursorLine: "Cursor lines",
    opponentRings: "Opponent rings",
    splitRings: "Split rings",
    virusRange: "Viruses range",
    teamIndicator: "Active cell indicator",
    commander: "Commander",
    chatType: "Chat type",
    targeting: "Cell Targeting [Spectate mode]",
    sounds: "Sounds",
    opt_on: "On",
    opt_off: "Off",
    opt_stepped: "Stepped",
    opt_linear: "Linear",
    opt_shortened: "Shortened",
    opt_full: "Full",
    opt_nick: "Nick",
    opt_mass: "Mass",
    opt_both: "Nick + Mass",
    opt_perf: "Performance",
    opt_normal: "Normal",
    opt_urlSkin: "Skins",
    opt_hsloSkin: "Astrio skins",
    opt_allSkin: "All skins",
    opt_singleClr: "Mono colored",
    opt_rainbow: "Rainbow",
    opt_onlyLines: "Only lines",
    opt_snowflakes: "Snowflakes",
    opt_chatroom: "Chatroom",
    opt_popup: "Pop up chat",
        autoSwitch: "Auto-switch Cells",
        eatAnimation: "Smooth Animation",
        backgroundImage: "Background Image",
        ownSkin: "Own Skin",
        uiScale: "UI Scale",
  },
  hkMenu: {
    title: "Hotkeys",
    toggleMenuKey: "Toggle main menu",
    feedKey: "Feed",
    macroFeedKey: "Macro feed",
    splitKey: "Split",
    doubleSplitKey: "Double split",
    tripleSplitKey: "Triple split",
    split16Key: "Split 16",
    split64Key: "Split 64",
    stopKey: "Stop cell movement",
    chatKey: "Toggle chat",
    freeSpectateKey: "Toggle spectate mode",
    toggleSplitRings: "Toggle split rings",
    toggleOpponentRings: "Toggle opponent rings",
    toggleNick: "Toggle cell nick",
    toggleMass: "Toggle cell mass",
    toggleTeamTags: "Toggle team tags",
    toggleHud: "Toggle HUD",
    toggleLbColors: "Toggle LB colors",
    toggleOwnNick: "Toggle own nick",
    toggleOwnMass: "Toggle own mass",
    toggleSkin: "Toggle all skins",
    toggleOwnSkin: "Toggle own skin",
    toggleFood: "Toggle food",
    command0Key: "Command 0",
    command1Key: "Command 1",
    command2Key: "Command 2",
    command3Key: "Command 3",
    command4Key: "Command 4",
    command5Key: "Command 5",
    command6Key: "Command 6",
    command7Key: "Command 7",
    command8Key: "Command 8",
    command9Key: "Command 9",
    zoom1key: "Zoom level 1",
    zoom2key: "Zoom level 2",
    zoom3key: "Zoom level 3",
    zoom4key: "Zoom level 4",
    zoom5key: "Zoom level 5",
        multiboxTab: "Switch multibox tab",
  },
  touchMenu: {
    title: "Touch controls",
    enable: "Enable touch controls",
    editor: "Key layout editor",
    edit: "Edit mode (drag & resize)",
    stickSize: "Joystick size",
    reset: "Reset layout",
    export: "Export layout",
    import: "Import layout",
        editorTitle: "Touch Editor",
        collapse: "Collapse",
        expand: "Expand",
        done: "Done",
        groupAdd: "Add",
        groupSelected: "Selected",
        groupStick: "Stick",
        add: "+ Add",
        resetStick: "Reset stick",
        size: "Size",
        noActions: "— no actions left —",
        copied: "✓ Copied",
        pasteJson: "Paste layout JSON:",
        importFail: "Invalid layout JSON",
        delete: "Delete",
        act_feed: "Feed once",
        act_macroFeed: "Feed continuously",
        act_split: "Split (1→2)",
        act_doubleSplit: "Double split (1→4)",
        act_tripleSplit: "Triple split (1→8)",
        act_split16: "Split ×16",
        act_split64: "Split ×64",
        act_commander: "Command mark",
        act_menu: "Show/hide menu",
        act_quickChat: "Quick chat",
        act_tabSwitch: "Multibox tab switch",
        act_stopMovement: "Stop movement",
        act_zoomIn: "Zoom in",
        act_zoomOut: "Zoom out",
  },
  mouseMenu: {
    title: "Mouse",
    feed: "Feed",
    macroFeed: "Macro feed",
    split: "Split",
    doubleSplit: "Double split",
    tripleSplit: "Triple split",
    split16: "Split 16",
    split64: "Split 64",
    commander: "Commander",
    off: "Off",
    lmb: "Left click",
    rmb: "Right click",
    scroll: "Middle click",
    targeting_h1: "Targeting",
    targeting_txt1: "Lock target 1",
    targeting_txt2: "Lock target 2",
    targeting_txt3: "Middle click or Toggle spectate key",
    targeting_txt4: "Toggle top cell mode to follow mouse mode",
    targeting_txt5: "Toggle targeting mode to follow mouse mode",
    targeting_txt6: "Toggle follow mouse mode to top cell mode",
  },
  commandsMenu: {
    title: "Commands",
    command0: "Help me!",
    command1: "Feed Me!",
    command2: "Split into me!",
    command3: "Need backup at %sector%!",
    command4: "Enemy spotted at %sector%!",
    command5: "Need a teammate!",
    command6: "Tank the virus!",
    command7: "Eat the virus!",
    command8: "Let's bait!",
    command9: "Fake tricksplit!",
  },
  themeMenu: {
    selectedPreset: "Theme preset",
    cursor: "Cursor",
    lbSize: "Leaderboard size",
    chatFontSize: "Chat font size",
    minimapSize: "Minimap size",
    skinBorder: "Skin border",
    cellTransparency: "Cell transparency",
    lightenCellColor: "Lighten cell color",
    borderColor: "Border color",
    borderWidth: "Border width",
    gridColor: "Grid color",
    gridTextColor: "Grid text color",
    gridTextSize: "Grid text size",
    gridTextFont: "Grid text font",
    gridWidth: "Grid width",
    nickColor: "Nick color",
    nickStrokeColor: "Nick stroke color",
    cellNickSize: "Nick size",
    nickFont: "Nick font",
    massColor: "Mass color",
    massStrokeColor: "Mass stroke color",
    cellMassSize: "Mass size",
    massFont: "Mass font",
    foodColor: "Food color",
    foodSize: "Food size",
    virusColor: "Virus color",
    virusBorderColor: "Virus border color",
    virusBorderWidth: "virus border width",
    virusDecor: "Virus Decoration",
    backgroundColor: "Background color",
    commanderColor: "Commander color",
    indicatorSize: "Active cell indicator size",
    team1color: "Team 1 color [Double Tag Mode]",
    team2color: "Team 2 color [Double Tag Mode]",
    on: "On",
    off: "Off",
        backgroundURL: "Background URL",
  },
};

export const langJA = {
  mainMenu: {
    btn_settings: "设定",
    btn_play: "プレー",
    btn_spectate: "観戦",
    btn_inputs: "インプット",
    btn_theme: "テーマ",
    input_tag1: "タグ",
    input_tag2: "タグ2",
    input_pin: "Pin",
    input_nick: "名前",
    input_skinUrl: "スキンURL (imgur)",
    select_ffa: "FFA",
    select_party: "パーティー",
    select_teams: "チーム",
    select_experimental: "エクスペリメンタル",
    input_token: "トークン",
    btn_join: "参加",
    btn_create: "作成",
  },
  notif: {
    cantPlay2Tag: "ダブルタグモードではプレーすることができません。",
    hsloNetConn: "Astrioネットワークに接続しました。",
    hsloNetDisconn: "Astrioネットワークから切断しました。",
    invalidSkinUrl: "無効なURLです。",
    login_lastSession: "最后のセッションからログインしました。",
    sdk_error: "SDKが読み込まれませんでした。",
    alreadyLoggedIn: "既にログインされています。",
    login_success: "ログインしました。",
    login_error: "ログインエラー！",
    logout: "ログアウトしました。",
    nickChangeInGame: "プレー中に名前を変更することはできません。",
    targeting_on: "マウスをクリックしてターゲットを始めます。マウス设定メニューの解説を参照。",
    targeting_off: "ターゲットがオフになりました。使用するには设定メニューからオンにしてください。",
    target_unnamed: "Cannot target unnamed cells.",
    hsloSkin_noAcc: "Account does not exist.",
  },
  leaderboard: {
    title: "Astr.io",
  },
  huds: {
    enterChatMsg: "メッセージを送信...",
    teamlist_title: "チームプレーヤー",
    score: "スコア",
    num1position: "1位の位置",
    paused: "静止",
    targeting_bigCellVp: "1位视点",
    targeting_followVp: "マウス视点",
    targeting_totalMass: "合計マス",
    targeting_players: "ターゲットプレーヤー",
  },
  settingMenu: {
    language: "言语",
    CellAnimation: "アニメーションディレイ",
    zoomSpeed: "ズーム速度",
    cameraSpeed: "カメラ速度 [2 デフォルト]",
    autoZoom: "オートズーム",
    autoHideText: "自动でテキストを隠す",
    teamTags: "Team Tags",
    hideHud: "Hide HUD",
    hideOwnNick: "Hide own nick",
    hideOwnMass: "Hide own mass",
    cellNick: "细胞の名前",
    cellMass: "细胞のマス",
    nickShadow: "影 [细胞の名前]",
    massShadow: "影 [细胞のマス]",
    urlSkins: "URLスキン",
    hsloSkins: "Astrioスキン",
    food: "粒",
    vanillaGrid: "バニラグリッド",
    bgSectors: "座标",
    activeTurnMarker: "Active cell border",
    cursorLine: "カーソルライン",
    opponentRings: "捕食判定リング",
    splitRings: "Split rings",
    virusRange: "棘范囲",
    teamIndicator: "Active cell indicator",
    commander: "コマンダー",
    chatType: "チャットタイプ",
    targeting: "ターゲット [観戦モード]",
    sounds: "サウンド",
    opt_on: "オン",
    opt_off: "オフ",
    opt_stepped: "ステップ",
    opt_shortened: "短縮",
    opt_linear: "リニア",
    opt_full: "フル",
    opt_nick: "名前",
    opt_mass: "マス",
    opt_both: "名前 + マス",
    opt_perf: "パフォーマンス",
    opt_normal: "ノーマル",
    opt_urlSkin: "URLスキン",
    opt_hsloSkin: "Astrioスキン",
    opt_allSkin: "全スキン",
    opt_singleClr: "単色",
    opt_rainbow: "レインボー",
    opt_onlyLines: "线のみ",
    opt_snowflakes: "スノーフレーク",
    opt_chatroom: "チャットルーム",
    opt_popup: "ポップアップチャット",
        autoSwitch: "自動切替",
        lbColors: "リーダーボードの色",
        eatAnimation: "スムーズアニメ",
        backgroundImage: "背景画像",
        ownSkin: "自分のスキン",
        uiScale: "UIスケール",
  },
  hkMenu: {
    title: "ホットキー",
    toggleMenuKey: "メインメニュー切り替え",
    feedKey: "餌",
    macroFeedKey: "餌マクロ",
    splitKey: "分裂",
    doubleSplitKey: "ダブル分裂",
    tripleSplitKey: "Triple Split",
    split16Key: "16分裂",
    split64Key: "64分裂",
    stopKey: "静止",
    chatKey: "チャット切り替え",
    freeSpectateKey: "観戦モード切り替え",
    toggleSplitRings: "Toggle split rings",
    toggleOpponentRings: "Toggle opponent rings",
    toggleNick: "名前表示切り替え",
    toggleMass: "マス表示切り替え",
    toggleSkin: "スキン表示切り替え",
    toggleFood: "餌表示切り替え",
    command0Key: "コマンド0",
    command1Key: "コマンド1",
    command2Key: "コマンド2",
    command3Key: "コマンド3",
    command4Key: "コマンド4",
    command5Key: "コマンド5",
    command6Key: "コマンド6",
    command7Key: "コマンド7",
    command8Key: "コマンド8",
    command9Key: "コマンド9",
    zoom1key: "ズームレベル1",
    zoom2key: "ズームレベル2",
    zoom3key: "ズームレベル3",
    zoom4key: "ズームレベル4",
    zoom5key: "ズームレベル5",
        toggleHud: "HUDの表示切替",
        toggleLbColors: "リーダーボードの色",
        toggleOwnMass: "自分の質量表示",
        toggleOwnNick: "自分の名前表示",
        toggleOwnSkin: "自分のスキン表示",
        toggleTeamTags: "チームタグ表示",
        multiboxTab: "マルチボックス切替",
  },
  touchMenu: {
    title: "タッチ操作",
    enable: "タッチ操作を有効化",
    editor: "キー配置エディタ",
    edit: "編集モード(ドラッグとリサイズ)",
    stickSize: "ジョイスティックサイズ",
    reset: "レイアウトリセット",
    export: "レイアウト書き出し",
    import: "レイアウト読み込み",
        editorTitle: "タッチエディタ",
        collapse: "折りたたむ",
        expand: "展開",
        done: "完了",
        groupAdd: "追加",
        groupSelected: "選択中",
        groupStick: "スティック",
        add: "+ 追加",
        resetStick: "スティック初期化",
        size: "サイズ",
        noActions: "— 利用可能な操作なし —",
        copied: "✓ コピー済み",
        pasteJson: "レイアウトJSONを貼り付け:",
        importFail: "レイアウトJSONが不正です",
        delete: "削除",
        act_feed: "一回フィード",
        act_macroFeed: "連続フィード",
        act_split: "分割(1→2)",
        act_doubleSplit: "ダブル分割(1→4)",
        act_tripleSplit: "トリプル分割(1→8)",
        act_split16: "16分割",
        act_split64: "64分割",
        act_commander: "コマンドマーク",
        act_menu: "メニュー表示切替",
        act_quickChat: "クイックチャット",
        act_tabSwitch: "マルチボックス切替",
        act_stopMovement: "移動停止",
        act_zoomIn: "ズームイン",
        act_zoomOut: "ズームアウト",
  },
  mouseMenu: {
    title: "マウス",
    feed: "餌",
    macroFeed: "餌マクロ",
    split: "分裂",
    doubleSplit: "ダブル分裂",
    tripleSplit: "Triple Split",
    split16: "16分裂",
    split64: "64分裂",
    commander: "コマンダー",
    off: "オフ",
    lmb: "左クリック",
    rmb: "右クリック",
    scroll: "スクロールクリック",
    targeting_h1: "ターゲット",
    targeting_txt1: "ターゲットロック1",
    targeting_txt2: "ターゲットロック2",
    targeting_txt3: "スクロールクリック or 観戦キー切り替え",
    targeting_txt4: "トップセルモードからマウス追跡に切り替え",
    targeting_txt5: "ターゲットモードからマウス追跡に切り替え",
    targeting_txt6: "マウス追跡からトップセルモードに切り替え",
  },
  commandsMenu: {
    title: "コマンド",
    command0: "Help me!",
    command1: "Feed Me!",
    command2: "Split into me!",
    command3: "Need backup at %sector%!",
    command4: "Enemy spotted at %sector%!",
    command5: "Need a teammate!",
    command6: "Tank the virus!",
    command7: "Eat the virus!",
    command8: "Let's bait!",
    command9: "Fake tricksplit!",
  },
  themeMenu: {
    selectedPreset: "Theme preset",
    cursor: "カーソル",
    lbSize: "リーダーボードの大きさ",
    chatFontSize: "Chat font size",
    minimapSize: "ミニマップの大きさ",
    skinBorder: "スキンの境界线",
    cellTransparency: "细胞の透過",
    lightenCellColor: "细胞色の軽减",
    borderColor: "境界线の色",
    borderWidth: "境界线の横幅",
    gridColor: "グリッドカラー",
    gridTextColor: "グリッドテキストカラー",
    gridTextSize: "グリッドテキストサイズ",
    gridTextFont: "グリッドテキストフォント",
    gridWidth: "グリッドの横幅",
    nickColor: "名前の色",
    nickStrokeColor: "名前の影の色",
    cellNickSize: "名前の大きさ",
    nickFont: "名前のフォント",
    massColor: "マスの色",
    massStrokeColor: "マスの影の色",
    cellMassSize: "マスの大きさ",
    massFont: "マスのフォント",
    foodColor: "フォントの色",
    foodSize: "粒の大きさ",
    virusColor: "棘の色",
    virusBorderColor: "棘の枠色",
    virusBorderWidth: "棘の境界线の横幅",
    virusDecor: "棘の装飾",
    backgroundColor: "背景色",
    commanderColor: "コマンダーの色",
    indicatorSize: "ﾁｰﾑﾒｲﾄｲﾝｼﾞｹｰﾀｰの大きさ",
    team1color: "チーム1の色 [ダブルタグモード]",
    team2color: "チーム2の色 [ダブルタグモード]",
    on: "オン",
    off: "オフ",
        backgroundURL: "背景URL",
  },
};

export const langZH = {
  mainMenu: {
    btn_settings: "设定",
    btn_play: "游玩",
    btn_spectate: "观战",
    btn_inputs: "输入",
    btn_theme: "主题",
    input_tag1: "队伍一",
    input_tag2: "队伍二",
    input_pin: "Pin",
    input_nick: "昵称",
    input_skinUrl: "皮肤网址 (imgur)",
    select_ffa: "自由混战",
    select_party: "组队",
    select_teams: "团队",
    select_experimental: "实验",
    input_token: "Party代码",
    btn_join: "加入",
    btn_create: "创建",
  },
  notif: {
    cantPlay2Tag: "不能用双重队伍",
    hsloNetConn: "连接Astrio网络",
    hsloNetDisconn: "断开Astrio网络",
    invalidSkinUrl: "不当皮肤网址",
    login_lastSession: "以上次资讯登入",
    sdk_error: "SDK未载入",
    alreadyLoggedIn: "已经登入",
    login_success: "登入成功",
    login_error: "登入错误",
    logout: "登出",
    nickChangeInGame: "不能在游戏中更改昵称.",
    targeting_on: "选取一细胞追踪。详看滑鼠设定介面的指引",
    targeting_off: "自动追踪模式已关闭，如要使用请在设定介面开启",
    target_unnamed: "无法锁定未命名的细胞。",
    hsloSkin_noAcc: "账号不存在。",
  },
  leaderboard: {
    title: "Astr.io",
  },
  huds: {
    enterChatMsg: "聊天输入中……",
    teamlist_title: "队伍玩家",
    score: "分数",
    num1position: "第一位置",
    paused: "暂停",
    targeting_bigCellVp: "最大玩家视野",
    targeting_followVp: "滑鼠跟随视野",
    targeting_totalMass: "总质量",
    targeting_players: "追踪玩家中",
  },
  settingMenu: {
    language: "语言",
    CellAnimation: "动画延迟",
    zoomSpeed: "变焦速度",
    cameraSpeed: "镜头速度［预设二］",
    autoZoom: "自动变焦",
    autoHideText: "自动隐藏文字",
    teamTags: "Team Tags",
    hideHud: "Hide HUD",
    hideOwnNick: "不显示自己质量",
    hideOwnMass: "不显示自己姓名",
    cellNick: "细胞昵称",
    cellMass: "细胞质量",
    nickShadow: "阴影 [细胞昵称]",
    massShadow: "阴影 [细胞质量]",
    urlSkins: "皮肤网址",
    hsloSkins: "Astrio皮肤",
    food: "食物",
    vanillaGrid: "原生格网",
    bgSectors: "背景区间",
    activeTurnMarker: "Active cell border",
    cursorLine: "导引线",
    opponentRings: "变色环",
    splitRings: "分裂距离圈",
    virusRange: "刺球距离",
    teamIndicator: "Active cell indicator",
    commander: "指挥",
    chatType: "聊天样式",
    targeting: "玩家追踪中 [观战模式]",
    sounds: "声音",
    opt_on: "开",
    opt_off: "关",
    opt_stepped: "阶跃式",
    opt_linear: "线性",
    opt_shortened: "简短化",
    opt_full: "全部",
    opt_nick: "昵称",
    opt_mass: "质量",
    opt_both: "昵称及质量",
    opt_perf: "效能",
    opt_normal: "一般",
    opt_urlSkin: "皮肤网址",
    opt_hsloSkin: "Astrio皮肤",
    opt_allSkin: "全部皮肤",
    opt_singleClr: "单色",
    opt_rainbow: "彩色",
    opt_onlyLines: "只有线条",
    opt_snowflakes: "雪花",
    opt_chatroom: "聊天栏",
    opt_popup: "弹出通知",
        autoSwitch: "自动切换细胞",
        lbColors: "排行榜颜色",
        eatAnimation: "平滑动画",
        backgroundImage: "背景图片",
        ownSkin: "自己的皮肤",
        uiScale: "界面缩放",
  },
  hkMenu: {
    title: "热键",
    toggleMenuKey: "切换主选单",
    feedKey: "单次喂养",
    macroFeedKey: "持续喂养",
    splitKey: "分裂",
    doubleSplitKey: "双重分裂",
    tripleSplitKey: "三重分裂",
    split16Key: "四重分裂",
    split64Key: "64 分裂",
    stopKey: "停止移动",
    chatKey: "切换聊天",
    freeSpectateKey: "切换观战模式",
    toggleSplitRings: "切换分裂距离圈",
    toggleOpponentRings: "切换变色环",
    toggleNick: "切换昵称显示",
    toggleMass: "切换质量显示",
    toggleSkin: "切换皮肤显示",
    toggleFood: "切换食物显示",
    command0Key: "指令０",
    command1Key: "指令１",
    command2Key: "指令２",
    command3Key: "指令３",
    command4Key: "指令４",
    command5Key: "指令５",
    command6Key: "指令６",
    command7Key: "指令７",
    command8Key: "指令８",
    command9Key: "指令９",
    zoom1key: "变焦等级一",
    zoom2key: "变焦等级二",
    zoom3key: "变焦等级三",
    zoom4key: "变焦等级四",
    zoom5key: "变焦等级五",
        toggleHud: "切换 HUD 显示",
        toggleLbColors: "切换排行榜颜色",
        toggleOwnMass: "显示自己的质量",
        toggleOwnNick: "显示自己的昵称",
        toggleOwnSkin: "显示自己的皮肤",
        toggleTeamTags: "显示队伍标签",
        multiboxTab: "多盒切换",
  },
  touchMenu: {
    title: "触屏控制",
    enable: "启用触屏控制",
    editor: "键位布局编辑器",
    edit: "编辑模式(拖动与缩放)",
    stickSize: "摇杆大小",
    reset: "重置布局",
    export: "导出布局",
    import: "导入布局",
        editorTitle: "触屏键位编辑器",
        collapse: "收起",
        expand: "展开",
        done: "完成",
        groupAdd: "添加",
        groupSelected: "选中",
        groupStick: "摇杆",
        add: "+ 添加",
        resetStick: "重置摇杆",
        size: "大小",
        noActions: "— 无可用动作 —",
        copied: "✓ 已复制",
        pasteJson: "粘贴布局 JSON:",
        importFail: "布局 JSON 无效",
        delete: "删除",
        act_feed: "单次喂食(吐一个孢子)",
        act_macroFeed: "持续喂食(按住连吐)",
        act_split: "分裂(1→2)",
        act_doubleSplit: "双连分(1→4)",
        act_tripleSplit: "三连分(1→8)",
        act_split16: "16 分",
        act_split64: "64 分(2^6 片)",
        act_commander: "指挥标记(拖动瞄准,松手标记)",
        act_menu: "显示/隐藏菜单",
        act_quickChat: "快捷指令(单点输入,拖动发预设)",
        act_tabSwitch: "多盒切换(tab1/tab2)",
        act_stopMovement: "停止移动(S 键等价)",
        act_zoomIn: "镜头拉近(视野缩小)",
        act_zoomOut: "镜头拉远(视野放大)",
  },
  mouseMenu: {
    title: "滑鼠",
    feed: "单次餵养",
    macroFeed: "持續餵养",
    split: "单次分裂",
    doubleSplit: "双重分裂",
    tripleSplit: "三重分裂",
    split16: "四重分裂",
    split64: "64 分裂",
    commander: "指挥",
    off: "关",
    lmb: "左键",
    rmb: "右键",
    scroll: "滚轮键",
    targeting_h1: "追踪中",
    targeting_txt1: "锁定目标一",
    targeting_txt2: "锁定目标二",
    targeting_txt3: "滚轮键或切换观战键",
    targeting_txt4: "切换最大玩家模式与滑鼠跟随模式",
    targeting_txt5: "切换自动追踪模式与滑鼠跟随模式",
    targeting_txt6: "切换滑鼠跟随模式与最大玩家模式",
  },
  commandsMenu: {
    title: "指令",
    command0: "操你妈！",
    command1: "喂我！",
    command2: "秒空给我！",
    command3: "%sector%需要支援！",
    command4: "%sector%发现敌人！",
    command5: "来个队友！",
    command6: "挡刺！",
    command7: "吃掉刺球！",
    command8: "来骗他！",
    command9: "装爆空骗他！",
  },
  themeMenu: {
    selectedPreset: "主题预设",
    cursor: "鼠标",
    lbSize: "排行榜大小",
    chatFontSize: "聊天室字体大小",
    minimapSize: "小地图大小",
    skinBorder: "皮肤轮廓",
    cellTransparency: "细胞透明度",
    lightenCellColor: "光亮细胞颜色",
    borderColor: "外围颜色",
    borderWidth: "外围阔度",
    gridColor: "区间颜色",
    gridTextColor: "区间文字颜色",
    gridTextSize: "区间文字大小",
    gridTextFont: "区间文字字型",
    gridWidth: "区间阔度",
    nickColor: "昵称颜色",
    nickStrokeColor: "昵称轮廓颜色",
    cellNickSize: "昵称大小",
    nickFont: "昵称字型",
    massColor: "质量讯息颜色",
    massStrokeColor: "质量讯息轮廓颜色",
    cellMassSize: "质量讯息大小",
    massFont: "质量讯息字型",
    foodColor: "食物颜色",
    foodSize: "食物大小",
    virusColor: "刺球颜色",
    virusBorderColor: "刺球外框颜色",
    virusBorderWidth: "刺球外框阔度",
    virusDecor: "刺球装饰",
    backgroundColor: "背景颜色",
    commanderColor: "指令颜色",
    indicatorSize: "队伍标示颜色",
    team1color: "队伍一颜色 [双队伍模式]",
    team2color: "队伍二颜色 [双队伍模式]",
    on: "开",
    off: "关",
        backgroundURL: "背景图片网址",
  },
};

export const langKO = {
  mainMenu: {
    btn_settings: "환경",
    btn_play: "플레이",
    btn_spectate: "관전",
    btn_inputs: "키보드",
    btn_theme: "테마",
    input_tag1: "태그",
    input_tag2: "태그 2",
    input_pin: "Pin",
    input_nick: "닉네임",
    input_skinUrl: "이미지 URL (imgur)",
    select_ffa: "FFA",
    select_party: "파티",
    select_teams: "팀",
    select_experimental: "익스페리멘탈",
    input_token: "파티 코드",
    btn_join: "조인",
    btn_create: "새로고침",
  },
  notif: {
    cantPlay2Tag: "태그2 모드에서는 실행할 수 없습니다..",
    NetConn: "Astrio 네트워크에 연결되었습니다.",
    hsloNetDisconn: "Astrio 네트워크에서 연결이 끊어졌습니다.",
    invalidSkinUrl: "잘못된 스킨 URL",
    login_lastSession: "마지막 세션 데이터에서 로그인했습니다..",
    sdk_error: "SDK가 로드되지 않았습니다.",
    alreadyLoggedIn: "이미 로그인 했습니다.",
    login_success: "로그인",
    login_error: "로그인 오류!",
    logout: "로그 아웃 됨!",
    nickChangeInGame: "게임 중 닉네임을 변경할 수 없습니다..",
    targeting_on: "타겟팅을 시작하려면 세포를 클릭하십시오. 마우스 설정에서 메뉴의 지침을 참조하십시요..",
    targeting_off: "타겟팅이 꺼져 있습니다. 설정 메뉴에서 사용하도록 설정하십시요.",
    target_unnamed: "Cannot target unnamed cells.",
    hsloSkin_noAcc: "Account does not exist.",
  },
  leaderboard: {
    title: "Astr.io",
  },
  huds: {
    enterChatMsg: "채팅 메세지 입력...",
    teamlist_title: "팀 플레이어",
    score: "점수",
    num1position: "#1등 위치",
    paused: "일시 중지",
    targeting_bigCellVp: "가장 큰 세포 목록",
    targeting_followVp: "마우스 타겟팅 설정",
    targeting_totalMass: "총 질량",
    targeting_players: "잠재적 타겟팅",
  },
  settingMenu: {
    language: "언어",
    CellAnimation: "애니메이션 지연",
    zoomSpeed: "줌 속도",
    cameraSpeed: "카메라 속도 [2 기본값]",
    autoZoom: "자동 확대/축소",
    autoHideText: "텍스트 자동 숨기기",
    teamTags: "Team Tags",
    hideHud: "Hide HUD",
    hideOwnNick: "Hide own nick",
    hideOwnMass: "Hide own mass",
    cellNick: "세포 닉네임",
    cellMass: "세포 질량",
    nickShadow: "그림자 [세포 닉네임]",
    massShadow: "그림자 [세포 질량]",
    urlSkins: "URL 스킨",
    hsloSkins: "Astrio 스킨",
    food: "먹이",
    vanillaGrid: "바닐라 무늬",
    bgSectors: "바탕화면",
    activeTurnMarker: "Active cell border",
    cursorLine: "커서 선",
    opponentRings: "질량 격자선",
    splitRings: "Split rings",
    virusRange: "바이러스 범위",
    teamIndicator: "Active cell indicator",
    commander: "위치 핑",
    chatType: "채팅 유형",
    targeting: "세포 타겟팅[관전 모드]",
    sounds: "소리",
    opt_on: "켜짐",
    opt_off: "꺼짐",
    opt_stepped: "닿은곳",
    opt_linear: "선형",
    opt_shortened: "짧은",
    opt_full: "전체",
    opt_nick: "닉네임",
    opt_mass: "질량",
    opt_both: "닉네임+ 질량",
    opt_perf: "실적",
    opt_normal: "보통",
    opt_urlSkin: "Url 스킨",
    opt_hsloSkin: "Astrio 스킨",
    opt_allSkin: "모든 스킨",
    opt_singleClr: "Mono colored",
    opt_rainbow: "무지개",
    opt_onlyLines: "테두리만",
    opt_snowflakes: "눈송이",
    opt_chatroom: "채팅방",
    opt_popup: "채팅 알림",
        autoSwitch: "자동 전환",
        lbColors: "리더보드 색상",
        eatAnimation: "부드러운 애니메이션",
        backgroundImage: "배경 이미지",
        ownSkin: "자기 스킨",
        uiScale: "UI 배율",
  },
  hkMenu: {
    title: "단축키",
    toggleMenuKey: "메인메뉴 끄기 ",
    feedKey: "feed 먹이",
    macroFeedKey: "매크로 feed먹이",
    splitKey: "분열",
    doubleSplitKey: "이중 분열",
    tripleSplitKey: "Triple Split",
    split16Key: "16분열",
    split64Key: "64분열",
    stopKey: "세포 이동중지",
    chatKey: "채팅 켜기",
    freeSpectateKey: "투사 모드 전환",
    toggleSplitRings: "Toggle split rings",
    toggleOpponentRings: "Toggle opponent rings",
    toggleNick: "세포 닉을 설정합니다",
    toggleMass: "세포 질량을 설정합니다",
    toggleSkin: "스킨 설정",
    toggleFood: "먹이 설정",
    command0Key: "명령 0",
    command1Key: "명령 1",
    command2Key: "명령 2",
    command3Key: "명령 3",
    command4Key: "명령 4",
    command5Key: "명령 5",
    command6Key: "명령 6",
    command7Key: "명령 7",
    command8Key: "명령 8",
    command9Key: "명령 9",
    zoom1key: "줌 수준 1",
    zoom2key: "줌 수준  2",
    zoom3key: "줌 수준 3",
    zoom4key: "줌 수준 4",
    zoom5key: "줌 수준 5",
        toggleHud: "HUD 표시 전환",
        toggleLbColors: "리더보드 색상 전환",
        toggleOwnMass: "자기 질량 표시",
        toggleOwnNick: "자기 닉네임 표시",
        toggleOwnSkin: "자기 스킨 표시",
        toggleTeamTags: "팀 태그 표시",
        multiboxTab: "멀티박스 전환",
  },
  touchMenu: {
    title: "터치 컨트롤",
    enable: "터치 컨트롤 사용",
    editor: "키 배치 에디터",
    edit: "편집 모드(드래그 및 크기 조절)",
    stickSize: "조이스틱 크기",
    reset: "레이아웃 초기화",
    export: "레이아웃 내보내기",
    import: "레이아웃 가져오기",
        editorTitle: "터치 에디터",
        collapse: "접기",
        expand: "펼치기",
        done: "완료",
        groupAdd: "추가",
        groupSelected: "선택됨",
        groupStick: "조이스틱",
        add: "+ 추가",
        resetStick: "조이스틱 초기화",
        size: "크기",
        noActions: "— 사용 가능한 동작 없음 —",
        copied: "✓ 복사됨",
        pasteJson: "레이아웃 JSON 붙여넣기:",
        importFail: "레이아웃 JSON이 잘못됨",
        delete: "삭제",
        act_feed: "한 번 먹이기",
        act_macroFeed: "연속 먹이기",
        act_split: "분할 (1→2)",
        act_doubleSplit: "이중 분할 (1→4)",
        act_tripleSplit: "트리플 분할 (1→8)",
        act_split16: "16 분할",
        act_split64: "64 분할",
        act_commander: "커맨드 마크",
        act_menu: "메뉴 표시/숨기기",
        act_quickChat: "빠른 채팅",
        act_tabSwitch: "멀티박스 전환",
        act_stopMovement: "이동 정지",
        act_zoomIn: "확대",
        act_zoomOut: "축소",
  },
  mouseMenu: {
    title: "마우스",
    feed: "피드feed",
    macroFeed: "매크로 피드feed",
    split: "분열",
    doubleSplit: "이중 분열",
    tripleSplit: "Triple Split",
    split16: "16 분열",
    split64: "64 분열",
    commander: "위치 핑",
    off: "꺼짐",
    lmb: "왼쪽 클릭",
    rmb: "오른쪽 클릭",
    scroll: "휠 클릭",
    targeting_h1: "타겟팅",
    targeting_txt1: "타겟 잠금 1  ",
    targeting_txt2: "타겟 잠금 2  ",
    targeting_txt3: "스크롤 클릭 or관전 키 전환",
    targeting_txt4: "정상 세포 모드에서 마우스 추적에 전환  ",
    targeting_txt5: "타겟 모드에서 마우스 추적에 전환  ",
    targeting_txt6: "마우스 추적에서 최고 세포 모드로 전환 ",
  },
  commandsMenu: {
    title: "명령어",
    command0: "시발!",
    command1: "빨리와주세요!",
    command2: "나에게 넣어줘!",
    command3: "여기에 도움요청 %sector%!",
    command4: "적 이곳에서 발견 %sector%!",
    command5: "팀원이 필요해!",
    command6: "바이러스 부셔!",
    command7: "바이러스 쏴!",
    command8: "미끼!",
    command9: "낚시하자",
  },
  themeMenu: {
    selectedPreset: "Theme preset",
    cursor: "커서",
    lbSize: "리더보드 크기",
    chatFontSize: "Chat font size",
    minimapSize: "미니맵 크기",
    skinBorder: "스킨 테두리",
    cellTransparency: "세포 투명도",
    lightenCellColor: "밝은 세포 색깔",
    borderColor: "테두리 색깔",
    borderWidth: "테두리 너비",
    gridColor: "눈금 색",
    gridTextColor: "격자 텍스트 색깔",
    gridTextSize: "눈금 텍스트 크기",
    gridTextFont: "격자 테스트 글꼴",
    gridWidth: "눈금 너비",
    nickColor: "닉네임 컬러",
    nickStrokeColor: "닉네임 색깔획",
    cellNickSize: "닉 크기",
    nickFont: "닉 글꼴",
    massColor: "질량 색깔",
    massStrokeColor: "질량 색깔획",
    cellMassSize: "질량 크기",
    massFont: "질량 글꼴",
    foodColor: "먹이 색깔",
    foodSize: "먹이 크기",
    virusColor: "바이러스 색깔",
    virusBorderColor: "바이러스 테두리 색",
    virusBorderWidth: "바이러스 테두리 너비",
    virusDecor: "바이러스 장식",
    backgroundColor: "배경 색깔",
    commanderColor: "위치 핑 색깔",
    indicatorSize: "팀 아이콘 크기",
    team1color: "팀 1 색[더블 태그 모드]",
    team2color: "팀 2 색[더블 태그 모드]",
    on: "켜짐",
    off: "꺼짐",
        backgroundURL: "배경 URL",
  },
};

export const langES = {
  mainMenu: {
    btn_settings: "Configuracion",
    btn_play: "Jugar",
    btn_spectate: "Espectear",
    btn_inputs: "Hot Keys",
    btn_theme: "Tema/Dise\xF1o",
    input_tag1: "Tag",
    input_tag2: "Tag 2",
    input_pin: "Pin",
    input_nick: "Nickname",
    input_skinUrl: "Skin URL (imgur)",
    select_ffa: "FFA",
    select_party: "Party",
    select_teams: "Teams",
    select_experimental: "Experimental",
    input_token: "Codigo Party",
    btn_join: "Entrar",
    btn_create: "Crear",
  },
  notif: {
    cantPlay2Tag: "Tu no puedes jugar cuando utilizas la funcion de doble tag.",
    hsloNetConn: "Conectado a Astrio",
    hsloNetDisconn: "Desconectado de Astrio",
    invalidSkinUrl: "Invalid skin URL",
    login_lastSession: "Logged in from last session data.",
    sdk_error: "SDK no ha cargado.",
    alreadyLoggedIn: "Ya te encuentras conectado.",
    login_success: "Conectado",
    login_error: "Error al conectar!",
    logout: "Desconectar",
    nickChangeInGame: "No puedes cambiar tu nickname cuando te encuentras jugando.",
    targeting_on: "Haga clic en una celula para comenzar a seguirla. Vea las instrucciones en el men\xFA de configuraci\xF3n del mouse.",
    targeting_off: "El seguimiento est\xE1 desactivada. Enci\xE9ndalo en el men\xFA de configuraci\xF3n para usarlo.",
    target_unnamed: "Cannot target unnamed cells.",
    hsloSkin_noAcc: "Account does not exist.",
  },
  leaderboard: {
    title: "Astr.io",
  },
  huds: {
    enterChatMsg: "Ingresa el mensaje...",
    teamlist_title: "Jugadores de equipo",
    score: "Puntuaci\xF3n",
    num1position: "#1 Posici\xF3n",
    paused: "Pausado",
    targeting_bigCellVp: "BIGGEST CELL VIEWPORT",
    targeting_followVp: "VIEWPORT FOLLOWING MOUSE",
    targeting_totalMass: "MASA TOTAL",
    targeting_players: "JUGADOR OBJETIVO",
  },
  settingMenu: {
    language: "Lenguaje",
    CellAnimation: "Retraso de animaci\xF3n",
    zoomSpeed: "Velocidad del Zoom",
    cameraSpeed: "Velocidad de Camara [2 es Preterminado]",
    autoZoom: "Auto zoom",
    autoHideText: "Auto Ocultar texto",
    teamTags: "Team Tags",
    hideHud: "Hide HUD",
    hideOwnNick: "Hide own nick",
    hideOwnMass: "Hide own mass",
    cellNick: "Nick de la celula",
    cellMass: "Masa de la celula",
    nickShadow: "Trazo del nick",
    massShadow: "Trazo del masa",
    urlSkins: "Skins",
    hsloSkins: "Skins",
    food: "Comida/Pellets",
    vanillaGrid: "Cuadricula Vanilla",
    bgSectors: "Tipo de sector",
    activeTurnMarker: "Active cell border",
    cursorLine: "Linea del cursor",
    opponentRings: "Rango del oponente",
    splitRings: "Split rings",
    virusRange: "Rango del virus",
    teamIndicator: "Active cell indicator",
    commander: "Se\xF1al/Comandante",
    chatType: "Tipo de Chat",
    targeting: "Seguiento de celula",
    sounds: "Sonidos",
    opt_on: "Activado",
    opt_off: "Desactivado",
    opt_stepped: "Stepped",
    opt_linear: "Lineal",
    opt_shortened: "Acortado",
    opt_full: "Completo",
    opt_nick: "Nick",
    opt_mass: "Masa",
    opt_both: "Nick + Masa",
    opt_perf: "Rendimiento",
    opt_normal: "Normal",
    opt_urlSkin: "Skins",
    opt_hsloSkin: "Skins",
    opt_allSkin: "Todas las skins",
    opt_singleClr: "Solo un color",
    opt_rainbow: "Arcoiris",
    opt_onlyLines: "Solo lineas",
    opt_snowflakes: "Copos de nieve",
    opt_chatroom: "Chatroom",
    opt_popup: "Chat emergente",
        autoSwitch: "Cambio automático",
        lbColors: "Colores del ranking",
        eatAnimation: "Animación suave",
        backgroundImage: "Imagen de fondo",
        ownSkin: "Skin propio",
        uiScale: "Escala de UI",
  },
  hkMenu: {
    title: "Hotkeys",
    toggleMenuKey: "Ocultar menu principal",
    feedKey: "Cebar",
    macroFeedKey: "Cebar rapido [Macro]",
    splitKey: "Dividirse",
    doubleSplitKey: "Divisi\xF3n doble",
    tripleSplitKey: "Divisi\xF3n triple",
    split16Key: "Dividir 16",
    split64Key: "Dividir 64",
    stopKey: "Detener el movimiento de la celula",
    chatKey: "Ocultar Chat",
    freeSpectateKey: "Toggle spectate mode",
    toggleSplitRings: "Toggle split rings",
    toggleOpponentRings: "Toggle opponent rings",
    toggleNick: "Ocultar nick de la celula",
    toggleMass: "Ocultar masa de la celula",
    toggleSkin: "Ocultar skin",
    toggleFood: "Ocultar comida/pellets",
    command0Key: "Comando 0",
    command1Key: "Comando 1",
    command2Key: "Comando 2",
    command3Key: "Comando 3",
    command4Key: "Comando 4",
    command5Key: "Comando 5",
    command6Key: "Comando 6",
    command7Key: "Comando  7",
    command8Key: "Comando 8",
    command9Key: "Comando 9",
    zoom1key: "Zoom nivel 1",
    zoom2key: "Zoom nivel 2",
    zoom3key: "Zoom nivel 3",
    zoom4key: "Zoom nivel 4",
    zoom5key: "Zoom nivel 5",
        toggleHud: "Mostrar/ocultar HUD",
        toggleLbColors: "Colores del ranking",
        toggleOwnMass: "Mostrar masa propia",
        toggleOwnNick: "Mostrar apodo propio",
        toggleOwnSkin: "Mostrar skin propio",
        toggleTeamTags: "Mostrar etiquetas de equipo",
        multiboxTab: "Cambiar pestaña multibox",
  },
  touchMenu: {
    title: "Controles tactiles",
    enable: "Activar controles tactiles",
    editor: "Editor de teclas",
    edit: "Modo edicion (arrastrar y redimensionar)",
    stickSize: "Tamano del joystick",
    reset: "Restablecer diseno",
    export: "Exportar diseno",
    import: "Importar diseno",
        editorTitle: "Editor táctil",
        collapse: "Plegar",
        expand: "Desplegar",
        done: "Hecho",
        groupAdd: "Añadir",
        groupSelected: "Seleccionado",
        groupStick: "Joystick",
        add: "+ Añadir",
        resetStick: "Restablecer joystick",
        size: "Tamaño",
        noActions: "— sin acciones —",
        copied: "✓ Copiado",
        pasteJson: "Pega el JSON del diseño:",
        importFail: "JSON de diseño no válido",
        delete: "Eliminar",
        act_feed: "Dar comida",
        act_macroFeed: "Comida continua",
        act_split: "División (1→2)",
        act_doubleSplit: "Doble división (1→4)",
        act_tripleSplit: "Triple división (1→8)",
        act_split16: "División ×16",
        act_split64: "División ×64",
        act_commander: "Marca de mando",
        act_menu: "Mostrar/ocultar menú",
        act_quickChat: "Chat rápido",
        act_tabSwitch: "Cambiar pestaña",
        act_stopMovement: "Detener movimiento",
        act_zoomIn: "Acercar",
        act_zoomOut: "Alejar",
  },
  mouseMenu: {
    title: "Raton",
    feed: "Cebar",
    macroFeed: "Cebar rapido[Macro]",
    split: "Division",
    doubleSplit: "Doble division",
    tripleSplitKey: "Triple division",
    split16: "Division por 16",
    split64: "Division por 64",
    commander: "Comandante",
    off: "Desactivado",
    lmb: "Clic izquierdo",
    rmb: "Clic derecho",
    scroll: "Clic central(Rueda)",
    targeting_h1: "Targeting",
    targeting_txt1: "Lock target 1",
    targeting_txt2: "Lock target 2",
    targeting_txt3: "Middle click or Toggle spectate key",
    targeting_txt4: "Toggle top cell mode to follow mouse mode",
    targeting_txt5: "Toggle targeting mode to follow mouse mode",
    targeting_txt6: "Toggle follow mouse mode to top cell mode",
        tripleSplit: "Triple división",
  },
  commandsMenu: {
    title: "Comandos",
    command0: "Mierda!",
    command1: "Alimentame!",
    command2: "Dividete en mi!",
    command3: "Necesito ayuda en %sector%!",
    command4: "Enemigo avistado en %sector%!",
    command5: "Necesito compa\xF1ero!",
    command6: "Lanza el virus!",
    command7: "Come el virus!",
    command8: "Haz baiteo!",
    command9: "Tricksplit falso!",
  },
  themeMenu: {
    selectedPreset: "Theme preset",
    cursor: "Puntero",
    lbSize: "Tama\xF1o del leaderboard",
    chatFontSize: "Chat font size",
    minimapSize: "Tama\xF1o del minimapa",
    skinBorder: "Borde de la Skin",
    cellTransparency: "Transparencia de la celula",
    lightenCellColor: "Claridad del color de la celula",
    borderColor: "Color del borde",
    borderWidth: "Ancho del borde",
    gridColor: "Color del grid",
    gridTextColor: "Color del texto del grid",
    gridTextSize: "Tama\xF1o de texto del grid",
    gridTextFont: "Fuente de texto del grid",
    gridWidth: "Ancho del grid",
    nickColor: "Color del nick",
    nickStrokeColor: "Color del borde del nick",
    cellNickSize: "Tama\xF1o del nick",
    nickFont: "Fuente del nick",
    massColor: "Color de la masa",
    massStrokeColor: "Color del borde de la masa",
    cellMassSize: "Tama\xF1o de la masa",
    massFont: "Fuente de la masa",
    foodColor: "Color de la comida",
    foodSize: "Tama\xF1o de la comida",
    virusColor: "Color del virus",
    virusBorderColor: "Color del borde del virus",
    virusBorderWidth: "Ancho del borde del virus",
    virusDecor: "Decoracion del virus",
    backgroundColor: "Color del fondo",
    commanderColor: "Color del comandante",
    indicatorSize: "Tama\xF1o del indicador de compa\xF1ero",
    team1color: "Color Equipo 1 [Modo doble TAG]",
    team2color: "Color Equipo 2 [Modo doble TAG]",
    on: "Activado",
    off: "Desactivado",
        backgroundURL: "URL de fondo",
  },
};

/** 语言代码 → 语言包(键与原 window.lang_<code> 一致)。 */
export default {
  EN: langEN,
  JA: langJA,
  ZH: langZH,
  KO: langKO,
  ES: langES,
};
